#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
zmodload zsh/zprof
# Customize to your needs...
export JAVA_HOME="`/usr/libexec/java_home -v 1.8`"
export PATH=$PATH:$JAVA_HOME/bin
export PATH="$PATH:$HOME/.rvm/bin"
#source $HOME/.rvm/scripts/rvm

# homebrew
export PATH=/usr/local/sbin:/usr/local/bin:$PATH

alias vim='reattach-to-user-namespace -l nvim'
export VISUAL='reattach-to-user-namespace -l nvim'
export EDITOR="$VISUAL"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
alias cat=bat

zprof
